repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3
  
  - repo: https://github.com/pycqa/pylint
    rev: v3.3.2
    hooks:
      - id: pylint
        args: [--rcfile=.pylintrc]
        additional_dependencies: [pylint==3.3.2]