"""Updated user model

Revision ID: bafe988616a8
Revises: 7f49a82285fc
Create Date: 2024-12-11 14:30:36.214976

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "bafe988616a8"
down_revision: Union[str, None] = "7f49a82285fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Pushes changes into the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("first_name", sa.String(length=50), nullable=False)
    )
    op.add_column("users", sa.Column("last_name", sa.String(length=50), nullable=False))
    op.add_column(
        "users", sa.Column("mobile_number", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "users", sa.Column("postal_address", sa.String(length=200), nullable=True)
    )
    op.add_column(
        "users", sa.Column("physical_address", sa.String(length=200), nullable=True)
    )
    op.add_column("users", sa.Column("country", sa.String(length=50), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "users", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_index("ix_users_username", table_name="users")
    op.drop_column("users", "username")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverts changes performed by upgrade()."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.create_index("ix_users_username", "users", ["username"], unique=True)
    op.drop_column("users", "updated_at")
    op.drop_column("users", "created_at")
    op.drop_column("users", "country")
    op.drop_column("users", "physical_address")
    op.drop_column("users", "postal_address")
    op.drop_column("users", "mobile_number")
    op.drop_column("users", "last_name")
    op.drop_column("users", "first_name")
    # ### end Alembic commands ###
