"""Updated contact model

Revision ID: d3375eff4ba1
Revises: bafe988616a8
Create Date: 2024-12-11 15:06:14.730466

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "d3375eff4ba1"
down_revision: Union[str, None] = "bafe988616a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Pushes changes into the database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contacts", sa.Column("contact_name", sa.String(length=100), nullable=False)
    )
    op.add_column("contacts", sa.Column("email", sa.String(), nullable=False))
    op.add_column(
        "contacts", sa.Column("contact_number", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "contacts",
        sa.Column("primary_contact_first_name", sa.String(length=50), nullable=False),
    )
    op.add_column(
        "contacts",
        sa.Column("primary_contact_last_name", sa.String(length=50), nullable=False),
    )
    op.add_column(
        "contacts",
        sa.Column(
            "primary_contact_contact_number", sa.String(length=20), nullable=True
        ),
    )
    op.add_column("contacts", sa.Column("categories", sa.String(), nullable=False))
    op.add_column("contacts", sa.Column("services", sa.String(), nullable=False))
    op.add_column("contacts", sa.Column("endorsements", sa.Integer(), nullable=True))
    op.drop_index("ix_contacts_name", table_name="contacts")
    op.drop_index("ix_contacts_service", table_name="contacts")
    op.create_index(
        op.f("ix_contacts_categories"), "contacts", ["categories"], unique=False
    )
    op.create_index(
        op.f("ix_contacts_contact_name"), "contacts", ["contact_name"], unique=False
    )
    op.create_index(op.f("ix_contacts_email"), "contacts", ["email"], unique=True)
    op.create_index(
        op.f("ix_contacts_services"), "contacts", ["services"], unique=False
    )
    op.drop_column("contacts", "service")
    op.drop_column("contacts", "name")
    op.drop_column("contacts", "rating")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverts changes performed by upgrade()."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contacts",
        sa.Column(
            "rating",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "contacts", sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "contacts",
        sa.Column("service", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_index(op.f("ix_contacts_services"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_email"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_contact_name"), table_name="contacts")
    op.drop_index(op.f("ix_contacts_categories"), table_name="contacts")
    op.create_index("ix_contacts_service", "contacts", ["service"], unique=False)
    op.create_index("ix_contacts_name", "contacts", ["name"], unique=False)
    op.drop_column("contacts", "endorsements")
    op.drop_column("contacts", "services")
    op.drop_column("contacts", "categories")
    op.drop_column("contacts", "primary_contact_contact_number")
    op.drop_column("contacts", "primary_contact_last_name")
    op.drop_column("contacts", "primary_contact_first_name")
    op.drop_column("contacts", "contact_number")
    op.drop_column("contacts", "email")
    op.drop_column("contacts", "contact_name")
    # ### end Alembic commands ###
