"""add timezone class to address failing tests

Revision ID: 794f4994f944
Revises: c222e5a52045
Create Date: 2024-12-30 10:35:34.345113

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "794f4994f944"
down_revision: Union[str, None] = "c222e5a52045"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Pushes changes into the database"""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Reverts changes performed by upgrade"""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
